package a.a.a;

import com.besome.sketch.beans.QuizBean;

import java.util.ArrayList;

public class tq {
    public static ArrayList<QuizBean> a;

    public static ArrayList<QuizBean> a() {
        if (a == null) {
            a = new ArrayList<>();
        }

        // X-O Questions
        a.add(new QuizBean("Компонент гироскопа поддерживается на каждом устройстве.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Индекс первого элемента в списке равен 1.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Сохраненные данные SharedPreference сохраняются даже при удалении приложения.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Сохраненные данные SharedPreference будут удалены после перезапуска приложения.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете получить доступ к событиям только со вкладки \"Событие\".", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете выполнять и отменять несколько задач по таймеру, используя один компонент таймера.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете использовать библиотеку Firebase, просто добавив ее на вкладку \"Компонент\".", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Внутри виджета макета \"Прокрутка\" можно разместить несколько виджетов.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Компонент SoundPool может воспроизводить любой звуковой файл любой длины.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Добавление Drawer или FAB в активити никак не влияет на время компиляции.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("В жизненном цикле действия \"onStop\" происходит после события \"onDestroy\".", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Удаление приложения Sketchware приведет к удалению всех сохраненных проектов.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Sketchware автоматически сохранит проект для вас.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("SharedPreferences и FileUtil делают то же самое.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете обновить приложение в Play Store, используя другой ключ выпуска.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Локальный проект, резервная копия которого не была создана, может быть восстановлен, если он будет удален.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("У виджетов может быть повторяющийся ID.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете отключить виджеты только с помощью его свойства \"enabled\".", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Свойство \"alpha\" создает тень позади виджета.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("В \"List\" может храниться только список чисел.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете проверить только одно условие внутри блока if-else.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Функция \"CLEAR_TOP\" компонента Intent удаляет самый верхний экран.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Блок \"finishActivity\" используется для закрытия приложения.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Невозможно программно прокрутить ListView с помощью блоков.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Невозможно открыть другие приложения с помощью компонента Intent.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Компонент ObjectAnimator - это единственный способ анимировать виджеты.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("После добавления компонента автоматически добавляются связанные с ним события.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Моя коллекция \"Project A\" недоступна из \"Project B.\".", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Можно загрузить APK-файл в Play Store без авторизации.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете удалить элементы \"Моей коллекции\" из менеджеров изображений, звука и шрифтов.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Обычно рекомендуется установить фиксированное значение dp для ширины и высоты виджета.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы не можете использовать другой виджет макета внутри макета.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы не можете установить максимальное количество строк, которые может отображать TextView.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы не можете отключить виджет EditText.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы не можете перенаправить пользователя на веб-сайт с помощью блоков.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете разделить число на 0.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы не можете копировать блоки в другие активити.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Календарь и CalendarView - это одно и то же.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете добавить только один компонент для каждого активити.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Имена переменных \"Abc\" и \"abc\" это одни и те же переменные.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы не можете добавлять повторяющиеся элементы в список.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете отменить действие по созданию переменной.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете создать виджет с повторяющимся ID.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете понизить код версии вашего приложения.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Событие жизненного цикла onCreate может быть удалено.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Удаленный проект можно восстановить.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Удаленный элемент коллекции может быть восстановлен.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Переменная, созданная в \"Активити A\", может быть доступна из \"Активити B\".", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("К компоненту, созданному в \"Активити А\", можно получить доступ из \"Активити В\".", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете использовать пользовательские блоки, созданные с помощью Sketchware Pro, в Sketchware из Google Play.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Файловые блоки работают на Android 11 и новее, если целевая версия SDK установлена на 30 и выше.", QuizBean.QUIZ_FALSE));
        a.add(new QuizBean("Вы можете выбрать файл с помощью компонента \"FilePicker\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Блок \"finishAffinity\" используется для закрытия приложения.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете добавить теги в AndroidManifest в менеджере AndroidManifest.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете создавать свои собственные компоненты в диспетчере компонентов.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете создать резервную копию одного проекта со всеми используемыми пользовательскими блоками и библиотеками.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете добавить Drawer в Менеджере видов.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете установить как \"изображение\", так и \"фоновый ресурс\" для ImageView.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете легко добавлять события на вкладке свойств, используя вкладку \"Событие\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете изменить цвет изображения с помощью блока \"setColorFilter\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Событие жизненного цикла onCreate - это первое, что вызывается при запуске приложения.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Попытка получить доступ к недопустимому ключу из Shared Preference может привести к сбою приложения.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете загружать и скачивать файлы с помощью Firebase Storage", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Чтобы присвоить значения элементам списка в ListView, вам необходимо добавить событие \"onBindView\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете изменять размер изображений на своем устройстве с помощью блоков FileUtil.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете изменить цвет строки состояния по умолчанию в расширенных настройках проекта.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете создать систему аутентификации при входе в систему, используя Firebase Auth.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете перекрывать виджеты, используя свойства перемещения и поворота.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Чтобы использовать библиотеку Firebase, вам необходимо сначала настроить конфигурацию в настройках библиотеки.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Свойство ImageView \"scaleType\" определяет соотношение размеров отображаемого изображения.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете создать пользовательский элемент списка для ListView.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Использование forever block без stop block приведет к зависанию и аварийному завершению работы приложения.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Блоки внутри блока if-then будут выполняться только в том случае, если условие истинно.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете хранить различные типы значений, используя \"Переменные\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Компонент Intent может использоваться для передачи данных между действиями.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Можно создать пользовательский элемент для ListView.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Моя коллекция - это общий набор данных для всех проектов.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Можно сохранять виджеты и блоки для последующего использования.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("При добавлении компонента добавляются новые блоки компонентов.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("MoreBlock это фиолетовый блок, который вы можете создать для повторяющихся задач.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете программно изменить стиль шрифта.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Существует сообщество Discord, которое может вам помочь.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете добавить событие onClick для других виджетов, отличных от кнопки.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы также можете добавлять события на вкладке \"Компонент\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете изменить языковые настройки Sketchware.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете отредактировать файл изображения после того, как он будет добавлен.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете экспортировать проект, чтобы продолжить работу в Android Studio.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете подписать проект, чтобы загрузить его в Play Store.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вам нужна учетная запись разработчика Play Store, чтобы загрузить свой APK-файл в Play Store.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете отцентрировать текст, используя свойство \"gravity\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете просмотреть переведенный исходный файл Java и XML.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете загружать фотографии в хранилище Firebase.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Чтобы поменять местами значения двух переменных, вам нужна третья переменная в качестве заполнителя.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Свойство Weight используется, когда вы хотите, чтобы размер вашего виджета соответствовал размеру экрана.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Блок trim на вкладке Оператор удаляет лишние пробелы в начале и в конце.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Можно изменить число на строку и наоборот.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете рассчитать ширину экрана, используя блоки.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете обнаружить коллизии различных виджетов, используя блоки \"getLocationX\" и \"getLocationY\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Флаг \"CLEAR_TOP\" компонента Intent удаляет все предыдущие действия в стеке навигации.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Флаг \"SINGLE_TOP\" компонента Intent повторно использует активити, а не создает новое, если оно существует в стеке навигации.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Блок \"startActivity\" используется для перехода к другому действию.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Чтобы воспроизводить звук с помощью SoundPool, вы должны сначала задать максимальное количество потоков.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете анимировать виджет с помощью компонента ObjectAnimator.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Некоторые компоненты поставляются со своими собственными событиями, которые вы можете добавить вручную.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете создать всплывающее сообщение с помощью диалогового компонента.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Компонент таймера не может быть отменен, если вы назначите ему более одной задачи.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете использовать MoreBlocks для более быстрой и эффективной разработки.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("You can share finished projects to other people without Sketchware.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Словесное оскорбление других членов сообщества может привести к блокировки.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете использовать MoreBlock внутри MoreBlock.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Можно добавить пользовательский шестнадцатеричный цветовой код.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете установить дополнительный набор изображений в ImageView, используя свойство \"фоновый ресурс\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("События в категории \"Drawer\" отображаются при добавлении виджета в файл \"drawer.xml\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Сервис Firebase от Google можно бесплатно использовать для небольших приложений.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Компонент камеры можно использовать для съемки фотографий.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете создать свой собственный валидатор для EditText, отредактировав событие \"onTextChanged\".", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете программно изменить стиль виджетов, используя блоки.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Свойство \"Подсказка\" для EditText подсказывает пользователю, что должно быть принято в качестве входных данных.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Параметр "НЕВИДИМЫЙ" для свойства видимости заставляет виджет исчезать, но все равно занимает место.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("В Sketchware можно создать ландшафтное приложение.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Звуковой файл можно бесконечно зацикливать.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы можете создавать алгоритмы с помощью блоков, например алгоритм, который перетасовывает колоду карт.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Событие \"onCreate\" - это первое событие жизненного цикла, которое возникает при запуске действия.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Вы не можете получить элемент из списка, используя индекс, превышающий размер списка.", QuizBean.QUIZ_TRUE));
        a.add(new QuizBean("Элементы в \"List\" упорядочены по времени сохранения.", QuizBean.QUIZ_TRUE));

        // Questions with options
        a.add(new QuizBean("Этот компонент используется для анимации виджетов.", QuizBean.QUIZ_ANSWER_B, "MediaPlayer", "ObjectAnimator"));
        a.add(new QuizBean("Этот компонент используется для воспроизведения более длинных звуковых файлов.", QuizBean.QUIZ_ANSWER_B, "SoundPool", "MediaPlayer"));
        a.add(new QuizBean("Это значение свойства width / height заполняет все заданное родительское пространство.", QuizBean.QUIZ_ANSWER_B, "WRAP_CONTENT", "MATCH_PARENT"));
        a.add(new QuizBean("Это свойство позволяет расположить дочерние элементы внутри макета.", QuizBean.QUIZ_ANSWER_A, "layout gravity", "gravity"));
        a.add(new QuizBean("Это свойство позволяет вам добавлять интервалы вокруг виджета.", QuizBean.QUIZ_ANSWER_B, "padding", "margin"));
        a.add(new QuizBean("Как вы можете изменить прозрачность фона?", QuizBean.QUIZ_ANSWER_A, "alpha", "background color"));
        a.add(new QuizBean("Как вы устанавливаете цифровой тип клавиатуры для EditText?", QuizBean.QUIZ_ANSWER_A, "ime", "numberDecimal"));
        a.add(new QuizBean("Какое событие жизненного цикла вызывается при перезапуске действия?", QuizBean.QUIZ_ANSWER_A, "onResume", "onStop"));
        a.add(new QuizBean("Какое свойство будет применено, если вы примените как \"singleLine=true\", так и \"lines=3\" к EditText?", QuizBean.QUIZ_ANSWER_A, "singleLine", "lines=3"));
        return a;
    }
}
